<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="wsit.HkdfGuard.Core.Test" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\wsit.HkdfGuard.Abstractions\wsit.HkdfGuard.Abstractions.csproj" />
    </ItemGroup>

</Project>
